### ISSUE TITLE
ERROR hooks

### ISSUE THREAD

**Issue by x5engine** [jaywilz/react-bootstrap-range-slider#2]
![image](https://user-images.githubusercontent.com/12363020/77573345-d0968600-6ed0-11ea-94b7-29bdb2c0788b.png)

**Comment by jaywilz** [comment]
Describe the bug and steps to reproduce, please?

**Comment by x5engine** [comment]
@jaywilz the bus is in the screenshot! 

how to reproduce: use it in a create react app and you will see this..

**Comment by jaywilz** [comment]
Did you install using `npm install` or did you build locally and use `npm link`? Or did you do something else?

If you used `npm link`, please see https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

_This problem can also come up when you use npm link or an equivalent. In that case, your bundler might “see” two Reacts — one in application folder and one in your library folder. Assuming myapp and mylib are sibling folders, one possible fix is to run npm link ../myapp/node_modules/react from mylib. This should make the library use the application’s React copy._
