### ISSUE TITLE
RangeSliderProps Optional Properties

### ISSUE THREAD

**Issue by TomPlum** [jaywilz/react-bootstrap-range-slider#22]
Thanks for the TS typings! Could we change some of `RangeSliderProps` to be optional please?

- `inputProps`: Is deprecated now due to prop forwarding and so shouldn't be enforced.
- `onChange` and `onAfterChange`: Consumers might only want to bind one of these events and not both.
- `tooltip` and `tooltipPlacement`: These defaulted before to `auto` and `bottom`. This would be nice, but no biggie.

Will raise a PR myself if I get around to it, but I think it's just a few question marks in the typings definition.

**Comment by jaywilz** [comment]
I must have forgot to hit `?` a few times!

Thanks for letting me know. It should be fixed in v3.0.1.
