### ISSUE TITLE
Failed to parse source map from ./node_modules/react-bootstrap-range-slider/dist/index.js

### ISSUE THREAD

**Issue by shubhdwiv12** [jaywilz/react-bootstrap-range-slider#28]
Hi, I am getting the following error after upgrading my react-scripts from 4.0.0 to 5.0.0 looks like it is not correctly parsing the source maps.

WARNING in ./node_modules/react-bootstrap-range-slider/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):

**Comment by Varinders0hal** [comment]
getting same issue @shubhdwiv12 do you find any solution ?

**Comment by jaywilz** [comment]
Sorry for the delay in fixing this. It should now be sorted (in version 3.0.4).
