### ISSUE TITLE
WebpackError: ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by isengartz** [jaywilz/react-bootstrap-range-slider#3]
**Describe the bug**
Whenever I try to build a production gatsby build it throws this error about the propTypes of ref props. Im using the package as followed below. I havent use the ref props as it isnt required and I dont need to.  Commenting out the ref propType everything works fine.

```
    <RangeSlider
      value={parseInt(value)}
      min={0}
      max={parseInt(props.max)}
      onChange={handleChange}
      tooltipLabel={currentValue => formatter.format(currentValue)}
      step={100}
      tooltipPlacement='top'
      variant="dark"
      tooltip="on"
    />
```

**To Reproduce**
run gatsby build when using the package

**Screenshots**
![range-slider](https://user-images.githubusercontent.com/10381621/79353585-e9c8aa80-7f43-11ea-96f0-086cab7266cf.jpg)

**Comment by jaywilz** [comment]
Thank you for reporting the issue - it should now be fixed.
