### ISSUE TITLE
RangeSlider is undefined after importing (when using webpack)

### ISSUE THREAD

**Issue by jkarshin** [jaywilz/react-bootstrap-range-slider#5]
Full disclosure that there is a very good chance this is a case of user-error, but I figured I'd create an issue in case you happen to have any insight. =)

**Describe the bug**
I'm using webpack along with typescript in my React project. I attempted to follow the steps on https://reactjsexample.com/a-range-slider-component-for-react-bootstrap/ to include your RangeSlider component, but React is complaining that RangeSlider is undefined:

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

The statement in my code that is causing the error is:

```
return (
            <RangeSlider value={42} onChange={(event: any) => this.handleSliderChanged(event)} />
        );
```

**To Reproduce**

Here's a trimmed down version of my file where I am able to reproduce the problem:

```
import * as React from "react";

import 'react-bootstrap-range-slider/dist/react-bootstrap-range-slider.css';
import RangeSlider from 'react-bootstrap-range-slider';

export class MyComponent extends React.Component<{}, {}> {
   
    handleSliderChanged(event: any) {
        // TODO implement
        console.log(event);
    }
    
    render() {
        return (
            <RangeSlider value={42} onChange={(event: any) => this.handleSliderChanged(event)} />
        );
    }
}
```

I ran `npm install react-bootstrap-range-slider` which added the following to my package.json:

```
    "react-bootstrap-range-slider": "^0.3.8",
```

and to my `package-lock.json`:

```
    "react-bootstrap-range-slider": {
      "version": "0.3.8",
      "resolved": "https://registry.npmjs.org/react-bootstrap-range-slider/-/react-bootstrap-range-slider-0.3.8.tgz",
      "integrity": "sha512-fvJ3vQUevIuuZNxVIFRSQo2rYq/KRnPy7MopB2bPD6/KfKjJrRTF3uiQ/PW5PsoiwteBoL5dG6lA6EhoUzY0fw==",
      "requires": {
        "classnames": "^2.2.6",
        "prop-types": "^15.7.2"
      }
    },
```

**Output/Result**
As mentioned above, this fails to render. By sticking a breakpoint on the return statement and stepping into the react code (react.development.js `createElementWithValidation`), I am able to see that the `type` is `undefined`.

I also stuck a breakpoint on the import statement for the `RangeSlider`, and what's weird is that in the Chrome debugger, it looks like the import is working. I stuck a breakpoint on the last line of `react-bootstrap-range-slider`'s `index.js` file, and according to the debugger, RangeSlider is initialized.

I stuck a `console.log(RangeSlider)` right after the import, but it prints `undefined`. Yet, if I stick a breakpoint on this log statement and mouse over `RangeSlider`, it appears to be initialized. No idea why the debugger is showing information that is inconsistent with the execution.

**Expected behavior**
Ideally, React would render the component =)

**Your Setup (if you think this information will be useful)**
 - Node.js version: 12.16.2
 - NPM version: 6.14.4
 - OS: Windows 10
 - Browser version: Chrome 83.0.4103.61
 - package.json: The relevant bits:

```
 "devDependencies": {
    "@types/react": "^16.9.35",
    "@types/react-dom": "^16.9.8",
    "css-loader": "^3.5.3",
    "source-map-loader": "^0.2.4",
    "style-loader": "^1.2.1",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.3",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    "bootstrap": "^4.5.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-bootstrap": "^1.0.1",
    "react-bootstrap-range-slider": "^0.3.8",
    "react-bootstrap-validation": "^0.1.11",
    "react-dom": "^16.13.1",
    "webpack-war-plugin": "^1.0.0-beta.3"
  }
```

webpack.config.js:

```
const { WebpackWarPlugin } = require('webpack-war-plugin');

module.exports = {
  mode: "production",

  // Enable sourcemaps for debugging webpack's output.
  devtool: "source-map",

  resolve: {
    // Add '.ts' and '.tsx' as resolvable extensions.
    extensions: [".ts", ".tsx"]
  },

  plugins: [
      new WebpackWarPlugin({
              additionalElements: [
                  { path: 'indexForWAR.html', destPath: 'index.html'}
              ]
      }),
  ],
  
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "ts-loader"
          }
        ]
      },
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
      // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
      {
        enforce: "pre",
        test: /\.js$/,
        loader: "source-map-loader"
      }
    ]
  },

  // When importing a module whose path matches one of the following, just
  // assume a corresponding global variable exists and use that instead.
  // This is important because it allows us to avoid bundling all of our
  // dependencies, which allows browsers to cache those libraries between builds.
  externals: {
    react: "React",
    "react-dom": "ReactDOM",
    "react-bootstrap": "ReactBootstrap",
    "prop-types": "PropTypes"
  }
};
```

Thanks in advance and sorry for the wall of text!

**Comment by jaywilz** [comment]
Have you made any progress on this?

If you could attach a zip containing a minimal example that reproduces the issue, I'll take a look.

**Comment by jkarshin** [comment]
I ended up switching from bootstrap to material-ui. I think my issue was that I didn't add the ".js" extension to the `resolve` block in my `webpack.config.js`. I don't know for certain if that would've fixed the issue, but I ended up having to do that to get material-ui to work.

Thanks though!
