### ISSUE TITLE
No After change event 

### ISSUE THREAD

**Issue by ajeesh-s** [jaywilz/react-bootstrap-range-slider#6]
First of all, nice job with the component.
while using react-bootstrap-range-slider i need to call api when the value changes , if i slide the value from 5 to 10 the change event get fired 5 times , the api call getting called in this. Can you please provide a after change event or slide start and end events ?

Values - 1 to 30 
step =1

**Comment by jaywilz** [comment]
Good suggestion! I'll aim to add the feature this week.

**Comment by jaywilz** [comment]
To keep things simple, I've added onAfterChange for now. I'll consider adding other callbacks.

It's worth noting, you can attach event listeners (the <input> element supports) using inputProps, for example:

```
<RangeSlider
  value={val}
  onChange={ev => setVal(ev.target.value)}
   inputProps={{
    onMouseDown={ev => console.log('Slide start')}
  }}
/>
```
