### ISSUE TITLE
It is maybe an error or bug ?

### ISSUE THREAD

**Issue by dpadula** [jaywilz/react-bootstrap-range-slider#7]
Do I need use react-bootstrap in a mandatory way? I'm currently using reactstrap and in slider the only variant that is not working , is "success".
All the others works perfectly.
Is that an error or bug ?
thanks

**Comment by jaywilz** [comment]
The success variant was incorrectly defined in the stylesheet. The issue should now be fixed (in version 1.1.3).

Thanks for letting me know!

**Comment by dpadula** [comment]
You're welcome.
