### ISSUE TITLE
Template tooltip spaces rare or unexpected behaviour

### ISSUE THREAD

**Issue by dpadula** [jaywilz/react-bootstrap-range-slider#8]
tooltipLabel={(currentValue) => \`${currentValue} min\`} this is rendered or visualized like only the number, but if you remove the space is rendered like '4min'.

Cheers

**Comment by jaywilz** [comment]
Another style issue - fixed in v1.1.4. The tooltip was missing a `nowrap` rule. Thanks again!

**Comment by dpadula** [comment]
Great. Glad to help here!
