### ISSUE TITLE
Slider doesn't respect Bootstrap custom sass theme

### ISSUE THREAD

**Issue by Johnhersh** [jaywilz/react-bootstrap-range-slider#9]
**Describe the bug**
Slider bar doesn't respect Bootstrap custom sass. Customizing the colors under $theme-colors works for the rest of the bootstrap elements, but not for the range slider. The instructions for this are from the [getting started page](https://react-bootstrap.github.io/getting-started/introduction).

**To Reproduce**
Using a custom sass with $theme-colors variables, then setting the primary to some other color. I have my range slider as such:
```js
<RangeSlider
  value={dissolveAmount}
  onChange={(changeEvent: any) => setDissolveAmount(changeEvent.target.value)}
  variant="primary"
/>
```
And in a custom scss file:
```css
$theme-colors: (
  "primary": tomato,
  "secondary": #000000,
);

// Import Bootstrap and its default variables
@import "~bootstrap/scss/bootstrap.scss";
```

**Output/Result (optional / if applicable)**
Slider remains blue.

**Expected behavior (optional)**
Slider should respect the custom theme.

**Additional context (optional)**
Is there any other way to override the default colors?

**Comment by jaywilz** [comment]
I'll aim to add support for SASS color overrides in the next couple of weeks.

In the meantime, as a workaround you can do something like this in your SASS:

`$variants: "primary", "secondary", "danger", "success", "danger", "warning", "info", "light", "dark";

@each $variant in $variants {

  input[type='range'].range-slider.range-slider--#{$variant} {
    
    &::-webkit-slider-thumb { background: theme-color($variant); }
    &::-moz-range-thumb { background: theme-color($variant); }
    &::-ms-thumb { background: theme-color($variant); }

  }

}`

**Comment by jaywilz** [comment]
The `$theme-colors` Sass variable should now be respected, as of v1.2.1.

I've added a [section in the readme](https://github.com/jaywilz/react-bootstrap-range-slider#sass--customizing-bootstrap).

**Comment by 7axiomsOfEuclid** [comment]
I tried to add custom colors but it didn't work. 
I wrote the following code in Slider. scss and import this file into my React component.
```
/* The following block can be included in a custom.scss */

/* make the customizations */
$theme-colors: (
    "info": tomato,
    "danger": teal
);

@import "react-bootstrap-range-slider/dist/react-bootstrap-range-slider.scss";

/* import bootstrap to set changes */
@import "~bootstrap/scss/bootstrap";
```
